# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-ECEF
version:      0.03
version_from: lib/Geo/ECEF.pm
installdirs:  site
requires:
    Geo::Ellipsoids:               0.06
    Geo::Functions:                0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
